name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: do-stuff
    runs-on: [self-hosted, linux, medium]
    steps:
        - name: DoSomthing
          run: echo $PATH
        - name: DoSomething2
          run: ${{ secrets.TEST_URL }}
