name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: do-stuff
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: DoSomthing
        run: echo $PATH
      - name: DoSomthing2
        run: git rev-parse HEAD
      - name: DoSomething3
        run: ${{ secrets.TEST_URL }}
